packages:
  - apps/*
  - packages/*

allowBuilds:
  msw: true
  protobufjs: true
  '@google/genai': true
  msgpackr-extract: true

onlyBuiltDependencies:
  - msw
  - protobufjs
  - '@google/genai'
  - msgpackr-extract

catalogMode: prefer

catalog:
  vite-plus: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
overrides: {vite: 'catalog:', vitest: 'npm:@voidzero-dev/vite-plus-test@latest'}
peerDependencyRules:
  allowAny: [vite, vitest]
  allowedVersions: {vite: '*', vitest: '*'}
