import {defineConfig} from 'vite-plus'

export default defineConfig({
	fmt: {
		ignorePatterns: ['**/*.gen.ts', '**/package.json'],

		arrowParens: 'avoid',
		bracketSpacing: false,
		objectWrap: 'collapse',
		printWidth: 120,
		semi: false,
		singleQuote: true,
		trailingComma: 'none',
		useTabs: true,

		sortTailwindcss: {functions: ['cn']},

		sortImports: {
			customGroups: [
				{elementNamePattern: ['@effect/**'], groupName: 'effectPackages', selector: 'external'},
				{elementNamePattern: ['effect'], groupName: 'effect', selector: 'external'},
				{elementNamePattern: ['@deslop/**'], groupName: 'aiToolkit', selector: 'external'},
				{elementNamePattern: ['@/**', '#*', '~/**'], groupName: 'aliases', selector: 'internal'}
			],
			groups: [
				['side_effect', 'side_effect_style'],
				{newlinesBetween: true},
				'builtin',
				{newlinesBetween: true},
				'effectPackages',
				'effect',
				{newlinesBetween: true},
				'external',
				{newlinesBetween: true},
				'aiToolkit',
				{newlinesBetween: true},
				'aliases',
				{newlinesBetween: true},
				'parent',
				'sibling',
				'index'
			],
			internalPattern: ['@/', '~/', '#', '@deslop/']
		}
	},
	lint: {
		categories: {
			correctness: 'off',
			nursery: 'off',
			pedantic: 'off',
			perf: 'off',
			restriction: 'off',
			style: 'off',
			suspicious: 'off'
		},
		env: {browser: true, builtin: true, node: true},
		ignorePatterns: ['**/*.gen.ts', '**/components/svgs/**', '**/components/ui/**', '**/generated/**'],
		jsPlugins: [
			{name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin'},
			{name: '@deslop/oxlint-rules', specifier: '@deslop/oxlint-rules/oxlint-plugin'}
		],
		options: {denyWarnings: true, reportUnusedDisableDirectives: 'deny', typeAware: true, typeCheck: true},
		overrides: [
			{files: ['**/*.config.ts'], rules: {'import/no-default-export': 'off'}},
			{
				files: ['packages/oxlint-rules/src/oxlint-plugin.ts'],
				rules: {'func-style': 'off', 'import/no-default-export': 'off'}
			},
			{files: ['**/*.tsx'], rules: {'unicorn/no-null': 'off'}}
		],
		plugins: ['eslint', 'typescript', 'oxc', 'import', 'react', 'unicorn'],
		rules: {
			'@deslop/oxlint-rules/no-access-alias': 'error',
			'@deslop/oxlint-rules/no-access-helper': 'error',
			'@deslop/oxlint-rules/no-atom-family-inferred-arg': 'error',
			'@deslop/oxlint-rules/no-composed-identity-key': 'error',
			'@deslop/oxlint-rules/no-condition-alias': 'error',
			'@deslop/oxlint-rules/no-data-class': 'error',
			'@deslop/oxlint-rules/no-declare-module-export': 'error',
			'@deslop/oxlint-rules/no-effect-returning-function': 'error',
			'@deslop/oxlint-rules/no-effect-run-entrypoint': 'error',
			'@deslop/oxlint-rules/no-exported-local-type': 'error',
			'@deslop/oxlint-rules/no-floating-local-type': 'error',
			'@deslop/oxlint-rules/no-forward-ref': 'error',
			'@deslop/oxlint-rules/no-function-return-type': 'error',
			'@deslop/oxlint-rules/no-identity-callback': 'error',
			'@deslop/oxlint-rules/no-iife': 'error',
			'@deslop/oxlint-rules/no-import-alias': 'error',
			'@deslop/oxlint-rules/no-json-global': 'error',
			'@deslop/oxlint-rules/no-let': 'error',
			'@deslop/oxlint-rules/no-local-mutable-holder': 'error',
			'@deslop/oxlint-rules/no-module-mutable-state': 'error',
			'@deslop/oxlint-rules/no-native-mutable-collection': 'error',
			'@deslop/oxlint-rules/no-native-prototype-method': 'error',
			'@deslop/oxlint-rules/no-nullary-effect-fn': 'error',
			'@deslop/oxlint-rules/no-nullary-effect-wrapper': 'error',
			'@deslop/oxlint-rules/no-nullish-comparison': 'error',
			'@deslop/oxlint-rules/no-object-destructure': 'error',
			'@deslop/oxlint-rules/no-option-constructor': 'error',
			'@deslop/oxlint-rules/no-optional-undefined-property': 'error',
			'@deslop/oxlint-rules/no-pass-through-wrapper': 'error',
			'@deslop/oxlint-rules/no-primitive-const': 'error',
			'@deslop/oxlint-rules/no-private-test-import': 'error',
			'@deslop/oxlint-rules/no-private-workspace-import': 'error',
			'@deslop/oxlint-rules/no-promise-callback': 'error',
			'@deslop/oxlint-rules/no-public-raw-domain-string': 'error',
			'@deslop/oxlint-rules/no-raw-tagged-object': 'error',
			'@deslop/oxlint-rules/no-schema-decoder-alias': 'error',
			'@deslop/oxlint-rules/no-schema-struct-const': 'error',
			'@deslop/oxlint-rules/no-single-use-guard': 'error',
			'@deslop/oxlint-rules/no-single-use-helper': 'error',
			'@deslop/oxlint-rules/no-static-return-function': 'error',
			'@deslop/oxlint-rules/no-typed-callback-params': 'error',
			'@deslop/oxlint-rules/no-useless-effect-wrapper': 'error',
			'@deslop/oxlint-rules/no-variable-type-annotation': 'error',
			'@deslop/oxlint-rules/no-zero-arg-effect-fn': 'error',
			'@deslop/oxlint-rules/prefer-match': 'error',
			'@typescript-eslint/array-type': ['error', {default: 'array'}],
			'@typescript-eslint/consistent-type-assertions': [
				'error',
				{arrayLiteralTypeAssertions: 'never', objectLiteralTypeAssertions: 'never'}
			],
			'@typescript-eslint/consistent-type-definitions': ['error', 'type'],
			'@typescript-eslint/consistent-type-exports': 'error',
			'@typescript-eslint/consistent-type-imports': [
				'error',
				{fixStyle: 'separate-type-imports', prefer: 'type-imports'}
			],
			'@typescript-eslint/no-confusing-non-null-assertion': 'error',
			'@typescript-eslint/no-confusing-void-expression': 'error',
			'@typescript-eslint/no-duplicate-type-constituents': 'error',
			'@typescript-eslint/no-empty-object-type': 'error',
			'@typescript-eslint/no-explicit-any': 'error',
			'@typescript-eslint/no-extra-non-null-assertion': 'error',
			'@typescript-eslint/no-floating-promises': 'error',
			'@typescript-eslint/no-inferrable-types': 'error',
			'@typescript-eslint/no-invalid-void-type': 'error',
			'@typescript-eslint/no-misused-promises': ['error', {checksVoidReturn: false}],
			'@typescript-eslint/no-namespace': ['error', {allowDeclarations: true}],
			'@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
			'@typescript-eslint/no-redundant-type-constituents': 'error',
			'@typescript-eslint/no-unnecessary-condition': 'error',
			'@typescript-eslint/no-unnecessary-template-expression': 'error',
			'@typescript-eslint/no-unnecessary-type-arguments': 'error',
			'@typescript-eslint/no-unnecessary-type-assertion': 'error',
			'@typescript-eslint/no-unnecessary-type-constraint': 'error',
			'@typescript-eslint/no-unnecessary-type-conversion': 'error',
			'@typescript-eslint/no-unnecessary-type-parameters': 'error',
			'@typescript-eslint/no-unsafe-argument': 'error',
			'@typescript-eslint/no-unsafe-assignment': 'error',
			'@typescript-eslint/no-unsafe-call': 'error',
			'@typescript-eslint/no-unsafe-member-access': 'error',
			'@typescript-eslint/no-unsafe-return': 'error',
			'@typescript-eslint/no-unsafe-type-assertion': 'error',
			'@typescript-eslint/no-useless-empty-export': 'error',
			'@typescript-eslint/non-nullable-type-assertion-style': 'error',
			'@typescript-eslint/prefer-as-const': 'error',
			'@typescript-eslint/prefer-nullish-coalescing': 'error',
			'@typescript-eslint/prefer-optional-chain': 'error',
			'@typescript-eslint/prefer-readonly': 'error',
			'@typescript-eslint/restrict-plus-operands': 'error',
			'@typescript-eslint/restrict-template-expressions': 'error',
			'@typescript-eslint/strict-boolean-expressions': 'error',
			'@typescript-eslint/strict-void-return': 'error',
			'@typescript-eslint/switch-exhaustiveness-check': 'error',
			'arrow-body-style': ['error', 'as-needed'],
			curly: ['error', 'multi-line', 'consistent'],
			'func-names': ['error', 'as-needed', {generators: 'never'}],
			'func-style': ['error', 'declaration'],
			'import/no-default-export': 'error',
			'import/no-duplicates': 'error',
			'import/no-empty-named-blocks': 'error',
			'import/no-mutable-exports': 'error',
			'import/no-self-import': 'error',
			'no-console': 'error',
			'no-else-return': 'error',
			'no-empty-function': ['error', {allow: ['arrowFunctions']}],
			'no-extra-boolean-cast': 'error',
			'no-implicit-coercion': 'error',
			'no-lonely-if': 'error',
			'no-negated-condition': 'error',
			'no-nested-ternary': 'error',
			'no-new-wrappers': 'error',
			'no-object-constructor': 'error',
			'no-param-reassign': ['error', {props: true}],
			'no-prototype-builtins': 'error',
			'no-restricted-globals': ['error', 'global', 'globalThis', 'String', 'Boolean', 'Array', 'Object', 'Reflect'],
			'no-restricted-imports': [
				'error',
				{
					paths: [
						{
							importNames: ['forwardRef', 'memo', 'useCallback', 'useMemo'],
							message: 'React Compiler handles refs and memoization. Remove manual wrappers.',
							name: 'react'
						}
					]
				}
			],
			'no-shadow': [
				'error',
				{allow: ['Array', 'Boolean', 'Console', 'Effect', 'HashMap', 'Number', 'Option', 'Schema', 'String']}
			],
			'no-throw-literal': 'error',
			'no-unneeded-ternary': 'error',
			'no-useless-call': 'error',
			'no-useless-concat': 'error',
			'no-useless-rename': 'error',
			'no-useless-return': 'error',
			'object-shorthand': 'error',
			'oxc/branches-sharing-code': 'error',
			'oxc/no-accumulating-spread': 'error',
			'oxc/no-map-spread': 'error',
			'prefer-const': ['error', {destructuring: 'all'}],
			'prefer-object-has-own': 'error',
			'prefer-object-spread': 'error',
			'prefer-regexp-test': 'error',
			'prefer-string-slice': 'error',
			'prefer-string-trim-start-end': 'error',
			'prefer-template': 'error',
			'react/exhaustive-deps': 'error',
			'react/jsx-key': 'error',
			'react/jsx-no-duplicate-props': 'error',
			'react/jsx-no-useless-fragment': 'error',
			'react/no-children-prop': 'error',
			'react/no-danger-with-children': 'error',
			'react/no-unstable-nested-components': ['error', {allowAsProps: true}],
			'react/react-compiler': 'error',
			'react/rules-of-hooks': 'error',
			'react/style-prop-object': 'error',
			'react/void-dom-elements-no-children': 'error',
			'require-await': 'error',
			'sort-keys': ['error', 'asc', {allowLineSeparatedGroups: true, natural: true}],
			'typescript/ban-ts-comment': ['error', {'ts-nocheck': true}],
			'unicorn/consistent-function-scoping': 'error',
			'unicorn/no-array-reverse': 'error',
			'unicorn/no-array-sort': 'error',
			'unicorn/no-null': 'error',
			'unicorn/no-object-as-default-parameter': 'error',
			'unicorn/no-static-only-class': 'error',
			'unicorn/no-useless-fallback-in-spread': 'error',
			'unicorn/no-useless-length-check': 'error',
			'unicorn/no-useless-promise-resolve-reject': 'error',
			'unicorn/no-useless-spread': 'error',
			'unicorn/no-useless-switch-case': 'error',
			'unicorn/no-useless-undefined': 'error',
			'unicorn/prefer-logical-operator-over-ternary': 'error',
			'unicorn/prefer-number-properties': 'error',
			'use-isnan': 'error',
			'vite-plus/prefer-vite-plus-imports': 'error'
		},
		settings: {react: {version: '19.0'}}
	},
	test: {environment: 'node', include: ['apps/*/src/**/*.test.ts', 'packages/*/src/**/*.test.ts'], pool: 'forks'}
})
