/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeWorktreeThreadRouteImport } from './routes/(home)/$worktree/thread'
import { Route as homeWorktreeTerminalRouteImport } from './routes/(home)/$worktree/terminal'
import { Route as homeWorktreeDiffRouteImport } from './routes/(home)/$worktree/diff'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeWorktreeThreadRoute = homeWorktreeThreadRouteImport.update({
  id: '/$worktree/thread',
  path: '/$worktree/thread',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeWorktreeTerminalRoute = homeWorktreeTerminalRouteImport.update({
  id: '/$worktree/terminal',
  path: '/$worktree/terminal',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeWorktreeDiffRoute = homeWorktreeDiffRouteImport.update({
  id: '/$worktree/diff',
  path: '/$worktree/diff',
  getParentRoute: () => homeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/$worktree/diff': typeof homeWorktreeDiffRoute
  '/$worktree/terminal': typeof homeWorktreeTerminalRoute
  '/$worktree/thread': typeof homeWorktreeThreadRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/$worktree/diff': typeof homeWorktreeDiffRoute
  '/$worktree/terminal': typeof homeWorktreeTerminalRoute
  '/$worktree/thread': typeof homeWorktreeThreadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(home)/$worktree/diff': typeof homeWorktreeDiffRoute
  '/(home)/$worktree/terminal': typeof homeWorktreeTerminalRoute
  '/(home)/$worktree/thread': typeof homeWorktreeThreadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$worktree/diff'
    | '/$worktree/terminal'
    | '/$worktree/thread'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$worktree/diff' | '/$worktree/terminal' | '/$worktree/thread'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/'
    | '/(home)/$worktree/diff'
    | '/(home)/$worktree/terminal'
    | '/(home)/$worktree/thread'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/$worktree/thread': {
      id: '/(home)/$worktree/thread'
      path: '/$worktree/thread'
      fullPath: '/$worktree/thread'
      preLoaderRoute: typeof homeWorktreeThreadRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/$worktree/terminal': {
      id: '/(home)/$worktree/terminal'
      path: '/$worktree/terminal'
      fullPath: '/$worktree/terminal'
      preLoaderRoute: typeof homeWorktreeTerminalRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/$worktree/diff': {
      id: '/(home)/$worktree/diff'
      path: '/$worktree/diff'
      fullPath: '/$worktree/diff'
      preLoaderRoute: typeof homeWorktreeDiffRouteImport
      parentRoute: typeof homeRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  homeWorktreeDiffRoute: typeof homeWorktreeDiffRoute
  homeWorktreeTerminalRoute: typeof homeWorktreeTerminalRoute
  homeWorktreeThreadRoute: typeof homeWorktreeThreadRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  homeWorktreeDiffRoute: homeWorktreeDiffRoute,
  homeWorktreeTerminalRoute: homeWorktreeTerminalRoute,
  homeWorktreeThreadRoute: homeWorktreeThreadRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
