/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as portfolioIndexRouteImport } from './routes/(portfolio)/index'
import { Route as PlaygroundInputIndexRouteImport } from './routes/playground/input/index'
import { Route as PlaygroundDiffIndexRouteImport } from './routes/playground/diff/index'
import { Route as PlaygroundChatIndexRouteImport } from './routes/playground/chat/index'

const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const portfolioIndexRoute = portfolioIndexRouteImport.update({
  id: '/(portfolio)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundInputIndexRoute = PlaygroundInputIndexRouteImport.update({
  id: '/input/',
  path: '/input/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundDiffIndexRoute = PlaygroundDiffIndexRouteImport.update({
  id: '/diff/',
  path: '/diff/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundChatIndexRoute = PlaygroundChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/': typeof portfolioIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/chat/': typeof PlaygroundChatIndexRoute
  '/playground/diff/': typeof PlaygroundDiffIndexRoute
  '/playground/input/': typeof PlaygroundInputIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof portfolioIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/playground/chat': typeof PlaygroundChatIndexRoute
  '/playground/diff': typeof PlaygroundDiffIndexRoute
  '/playground/input': typeof PlaygroundInputIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/(portfolio)/': typeof portfolioIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/chat/': typeof PlaygroundChatIndexRoute
  '/playground/diff/': typeof PlaygroundDiffIndexRoute
  '/playground/input/': typeof PlaygroundInputIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/playground'
    | '/'
    | '/playground/'
    | '/playground/chat/'
    | '/playground/diff/'
    | '/playground/input/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/playground/chat'
    | '/playground/diff'
    | '/playground/input'
  id:
    | '__root__'
    | '/playground'
    | '/(portfolio)/'
    | '/playground/'
    | '/playground/chat/'
    | '/playground/diff/'
    | '/playground/input/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlaygroundRouteRoute: typeof PlaygroundRouteRouteWithChildren
  portfolioIndexRoute: typeof portfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/(portfolio)/': {
      id: '/(portfolio)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof portfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/input/': {
      id: '/playground/input/'
      path: '/input'
      fullPath: '/playground/input/'
      preLoaderRoute: typeof PlaygroundInputIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/diff/': {
      id: '/playground/diff/'
      path: '/diff'
      fullPath: '/playground/diff/'
      preLoaderRoute: typeof PlaygroundDiffIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/chat/': {
      id: '/playground/chat/'
      path: '/chat'
      fullPath: '/playground/chat/'
      preLoaderRoute: typeof PlaygroundChatIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
  }
}

interface PlaygroundRouteRouteChildren {
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  PlaygroundChatIndexRoute: typeof PlaygroundChatIndexRoute
  PlaygroundDiffIndexRoute: typeof PlaygroundDiffIndexRoute
  PlaygroundInputIndexRoute: typeof PlaygroundInputIndexRoute
}

const PlaygroundRouteRouteChildren: PlaygroundRouteRouteChildren = {
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  PlaygroundChatIndexRoute: PlaygroundChatIndexRoute,
  PlaygroundDiffIndexRoute: PlaygroundDiffIndexRoute,
  PlaygroundInputIndexRoute: PlaygroundInputIndexRoute,
}

const PlaygroundRouteRouteWithChildren = PlaygroundRouteRoute._addFileChildren(
  PlaygroundRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlaygroundRouteRoute: PlaygroundRouteRouteWithChildren,
  portfolioIndexRoute: portfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
