/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeRealtimeIndexRouteImport } from './routes/(home)/realtime/index'
import { Route as homeDiffIndexRouteImport } from './routes/(home)/diff/index'
import { Route as homeChatIndexRouteImport } from './routes/(home)/chat/index'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRealtimeIndexRoute = homeRealtimeIndexRouteImport.update({
  id: '/realtime/',
  path: '/realtime/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeDiffIndexRoute = homeDiffIndexRouteImport.update({
  id: '/diff/',
  path: '/diff/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeChatIndexRoute = homeChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => homeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/chat/': typeof homeChatIndexRoute
  '/diff/': typeof homeDiffIndexRoute
  '/realtime/': typeof homeRealtimeIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof homeChatIndexRoute
  '/diff': typeof homeDiffIndexRoute
  '/realtime': typeof homeRealtimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(home)/chat/': typeof homeChatIndexRoute
  '/(home)/diff/': typeof homeDiffIndexRoute
  '/(home)/realtime/': typeof homeRealtimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chat/' | '/diff/' | '/realtime/'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat' | '/diff' | '/realtime'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/chat/'
    | '/(home)/diff/'
    | '/(home)/realtime/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/realtime/': {
      id: '/(home)/realtime/'
      path: '/realtime'
      fullPath: '/realtime/'
      preLoaderRoute: typeof homeRealtimeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/diff/': {
      id: '/(home)/diff/'
      path: '/diff'
      fullPath: '/diff/'
      preLoaderRoute: typeof homeDiffIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/chat/': {
      id: '/(home)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof homeChatIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeChatIndexRoute: typeof homeChatIndexRoute
  homeDiffIndexRoute: typeof homeDiffIndexRoute
  homeRealtimeIndexRoute: typeof homeRealtimeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeChatIndexRoute: homeChatIndexRoute,
  homeDiffIndexRoute: homeDiffIndexRoute,
  homeRealtimeIndexRoute: homeRealtimeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
