name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          docker build -t ghcr.io/${REPO}-template:latest ./apps/template
          docker push ghcr.io/${REPO}-template:latest

      - name: Dokploy Deploy
        run: |
          curl -X POST https://dev.mp281x.xyz/api/application.deploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}" \
            -d '{"applicationId": "qjFRER0koB-vnn_hjkMm-"}'
