name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bun
        uses: oven-sh/setup-bun@v2.1.3

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Docker Login
        uses: docker/login-action@v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: ./apps/portfolio
          tags: ghcr.io/mp281x/${{ github.event.repository.name }}-portfolio:latest
