name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bun
        uses: oven-sh/setup-bun@v2.1.3

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Docker Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push Portfolio
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v7
        with:
          push: true
          context: ./apps/portfolio
          tags: ghcr.io/mp281x/${{ github.event.repository.name }}-portfolio:latest

      - name: Docker Build and Push Agent
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v7
        with:
          push: true
          context: ./apps/agent
          tags: ghcr.io/mp281x/${{ github.event.repository.name }}-agent:latest

      - name: Dokploy Portfolio
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://dev.mp281x.xyz/api/application.deploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}" \
            -d '{"applicationId": "EuAZczmhLkuLvASm3QRTz"}'

      - name: Dokploy Agent
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://dev.mp281x.xyz/api/application.deploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}" \
            -d '{"applicationId": "iD8YNp8nSkHVIdmp6kmB0"}'
